### ISSUE TITLE
mod-script-pipe unusable

### ISSUE THREAD

**Issue by SteveDaulton** [probonopd/audacity#21]
Testing on Xubuntu 20.04 LTS.
mod-script-pipe cannot be reached even though enabled in Modules Preferences.

**Comment by probonopd** [comment]
Hello @SteveDaulton, thanks for your report; however I am no longer working on this since the https://github.com/audacity/audacity project did not seem to be interested in publishing and supporting an offical Audacity AppImage. We can look into this again should the project decide to publish and support an AppImage.
