### ISSUE TITLE
PulseAudio unavailable

### ISSUE THREAD

**Issue by SteveDaulton** [probonopd/audacity#22]
Testing with Xubuntu 20.04 LTS

"Pulse" does not appear as a recording / playback option. This should be the default.

**Comment by probonopd** [comment]
Hello @SteveDaulton, thanks for your report; however I am no longer working on this since the https://github.com/audacity/audacity project did not seem to be interested in publishing and supporting an offical Audacity AppImage. We can look into this again should the project decide to publish and support an AppImage.
